# Generated by Django 4.2.10 on 2024-03-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_review_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
